# 01 - NumPy Basics

### Files:
| Notebook | Description |
|---------|-------------|
| 01_basics.ipynb | Installing and importing NumPy, why NumPy is faster, array vs list. Creating arrays, inspecting shape, dtype, size |

### Learning Objectives:
- Understand what NumPy is and why it’s essential in Data Science.
- Learn how NumPy stores data in continuous memory.
- Create 1D, 2D, and multi-dimensional arrays.



In [1]:
import numpy as np

# What is NumPy?
print("NumPy version:", np.__version__)


NumPy version: 2.3.4


In [2]:
# Lists vs NumPy Arrays (Speed Difference Demo)
import time

size = 1_000_000
list_data = list(range(size))
array_data = np.arange(size)

start = time.time()
sum(list_data)
end = time.time()
print("List sum time:", end - start)

start = time.time()
np.sum(array_data)
end = time.time()
print("NumPy sum time:", end - start)


List sum time: 0.01910686492919922
NumPy sum time: 0.0


Key Concept:

NumPy arrays are stored in **continuous memory blocks** and use **vectorized operations** in C, which makes them extremely fast compared to Python lists.


In [3]:
# Creating Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
# Checking shape and dimensions
print(arr1.shape, arr1.ndim)
print(arr2.shape, arr2.ndim)


(3,) 1
(2, 3) 2


In [5]:
# Common array creation methods
zeros = np.zeros((2,3))
ones = np.ones((3,3))
range_arr = np.arange(1, 10, 2)
lin = np.linspace(0,1,5)

print(zeros)
print(ones)
print(range_arr)
print(lin)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
