# 02 - NumPy Operations

In this section, we learn how to:
- Perform mathematical operations on arrays
- Use element-wise operations
- Use aggregation functions (sum, mean, max, min)
- Apply comparisons and Boolean operations


1) Element-wise operations

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


2) Scalar operations

In [2]:
print(a + 10)
print(a * 2)
print(a / 5)


[20 30 40 50]
[20 40 60 80]
[2. 4. 6. 8.]


3) Mathematical functions

In [3]:
print(np.log(a))
print(np.sqrt(a))
print(np.exp(a))


[2.30258509 2.99573227 3.40119738 3.68887945]
[3.16227766 4.47213595 5.47722558 6.32455532]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


4) Aggregations (very important for Data Science)

In [4]:
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(data.sum())
print(data.sum(axis=0))  # column-wise
print(data.sum(axis=1))  # row-wise

print(data.mean())
print(data.max())
print(data.min())
print(np.median(data))


21
[5 7 9]
[ 6 15]
3.5
6
1
3.5


5) Boolean operations

In [5]:
print(a > 20)
print(a[a > 20])  # filter values


[False False  True  True]
[30 40]
