# 03 - Advanced NumPy

In this section, we will master:
- Indexing & slicing arrays
- Boolean indexing & filtering
- Fancy indexing
- Reshaping, flattening, ravel()
- Transpose and axis operations
- Broadcasting rules and patterns


1) Indexing & Slicing

In [1]:
import numpy as np

arr = np.arange(1, 11)
print(arr)

# Slicing
print(arr[0:5])     # first 5 elements
print(arr[5:])      # from index 5 to end
print(arr[:5])      # first 5 elements
print(arr[::-1])    # reverse array

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]
[10  9  8  7  6  5  4  3  2  1]


In [2]:
# 2D Indexing
m = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(m[0, 0])  # row 0, col 0
print(m[1, 2])  # row 1, col 2
print(m[:, 1])  # second column
print(m[1, :])  # second row


10
60
[20 50 80]
[40 50 60]


2) Boolean Indexing (This is what makes pandas filtering work)

In [3]:
arr = np.array([10, 25, 3, 37, 50, 7])

print(arr[arr > 20])
print(arr[arr % 2 == 0])
print(arr[(arr > 10) & (arr < 40)])  # chaining conditions


[25 37 50]
[10 50]
[25 37]


This is how you do WHERE in SQL using NumPy.
If you don’t master this, you’ll stay a pandas amateur.

3) Fancy Indexing

In [4]:
arr = np.array([100, 200, 300, 400, 500])
idx = [0, 2, 4]

print(arr[idx])  # picks 100, 300, 500


[100 300 500]


In [5]:
m = np.arange(1, 17).reshape(4,4)
print(m[[0, 2], :])      # pick rows 0 and 2
print(m[:, [1, 3]])      # pick columns 1 and 3


[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


4) Reshape / Ravel / Flatten / Transpose

In [6]:
arr = np.arange(1, 13)

print(arr.reshape(3, 4))
print(arr.reshape(2, 6))

print(arr.reshape(-1, 1))  # IMPORTANT for sklearn
print(arr.reshape(1, -1))  # row vector

print(arr.ravel())  # returns view (no memory copy)
print(arr.flatten())  # returns copy


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
m = np.arange(1, 13).reshape(3,4)
print(m.T)  # transpose


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


5) Broadcasting (Core skill for ML)

If you don't get this → you will never write optimized NumPy code.

Example 1:

In [8]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])

v = np.array([10, 20, 30])

print(m + v)


[[11 22 33]
 [14 25 36]]


Example 2 (Broadcast over rows):

In [9]:
col = np.array([[10],
                [20]])

print(m + col)


[[11 12 13]
 [24 25 26]]


Broadcasting Rule Summary (write this in markdown after you understand it):

Broadcasting works when:
- Dimensions are equal, or
- One dimension is 1
