# 05 - Vectorization & Performance

Goal:
- Stop using Python loops for array computations
- Write optimized, pure NumPy solutions
- Understand when and why vectorization works


1) Vectorized vs Loop Example (Time Difference)

In [1]:
import numpy as np
import time

arr = np.random.randint(1, 100, size=1_000_000)

# Python loop
start = time.time()
out1 = [x * 2 for x in arr]
end = time.time()
print("Python loop time:", end - start)

# NumPy vectorized
start = time.time()
out2 = arr * 2
end = time.time()
print("NumPy vectorized time:", end - start)


Python loop time: 0.10970234870910645
NumPy vectorized time: 0.002004861831665039


If the speed difference does not shock you, re-run it.

2) Replacing Condition-Based Loops


Bad Python way:

In [5]:
arr = np.array([10, 40, 15, 5, 90, 2])
out = []

for x in arr:
    if x > 20:
        out.append(x)
out


[np.int64(40), np.int64(90)]

Good NumPy way:

In [ ]:
out = arr[arr > 20]
print(out)


[40 90]


3) Apply Formula to Entire Dataset

Imagine feature scaling without loops:

In [6]:
data = np.random.randn(1000, 3) * 10 + 50

scaled = (data - data.mean(axis=0)) / data.std(axis=0)
scaled[:5]


array([[-0.71378597, -0.81951702,  0.49436274],
       [ 0.15338972, -0.98373866,  2.08763052],
       [ 1.47795345, -0.5337118 , -1.28831965],
       [ 0.91070302,  0.24547518, -0.81940022],
       [ 0.22166805, -0.5936246 , -0.40953821]])

If you don’t have mental model of axis, you won’t survive ML.

4) Vectorized Custom Function (Key Skill)

We define a function and map it without loops:

In [7]:
def relu(x):
    return np.maximum(0, x)

x = np.array([-5, -1, 0, 3, 8])
print(relu(x))


[0 0 0 3 8]


This is how neural networks activate neurons.
If you don't get this → you can't understand deep learning.

5) Real Applied Task (You do this — I will check)

Dataset:

In [8]:
scores = np.array([52, 61, 98, 35, 75, 88, 44, 69])


Task (No loops allowed):

Curve score: score + 10

Convert to GPA scale (0 to 4):

In [10]:
curved = scores + 10
gpa = (curved - curved.min()) / (curved.max() - curved.min()) * 4
gpa[gpa >= 3.0]


array([4.        , 3.36507937])