# 06 - Matrix Operations (Critical for ML & Neural Networks)

Topics:
- Dot products (core of regression models)
- Matrix multiplication (weights × inputs)
- Identity matrix & inverse
- Solving linear systems (real use case: regression coefficients)


1) Dot Product (This is how neural networks compute)

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))


32


2) Matrix Multiplication (weights × features)

In [2]:
W = np.array([[1, 2],
              [3, 4],
              [5, 6]])

x = np.array([[10],
              [20]])

print(W @ x)


[[ 50]
 [110]
 [170]]


3) Identity Matrix + Inverse

In [3]:
I = np.eye(3)
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)
print(A_inv)
print(A @ A_inv)  # should ≈ identity


[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


4) Solve Linear Equation Ax = b (like regression normal equation)

In [4]:
A = np.array([[3, 1],
              [1, 2]])

b = np.array([9, 8])

x = np.linalg.solve(A, b)
print(x)


[2. 3.]
